---
  - name: Check if operating system upgrade is needed
    command: /usr/lib/update-notifier/apt-check --package-names
    register: stale

  - name: Upgrade the system
    apt:
      update_cache: yes
      upgrade: dist
    when: stale.stderr != ""

  - name: Reboot if needed
    command: /sbin/reboot removes=/var/run/reboot-required
    async: 0
    poll: 0
    ignore_errors: true

  - name: Check if host is up
