---
  - name: Run common roles
    hosts:
      - all
    roles:
      - root-access
      - custom-repos
      - ntp
      - dist-upgrade
      - zabbix-agent

  - name: Install passenger and nginx
    hosts:
      - web
    roles:
      - passenger
      - nginx

  - name: Install cassandra
    hosts:
      - cassandra
    roles:
      - cassandra

  - name: Install kafka and zookeeper
    hosts:
      - queue
    roles:
      - kafka

  - name: Install postgresql
    hosts:
      - postgres
    roles:
      - postgresql
