---
  - name: Make oracle eula to be accepted
    debconf:
      name: oracle-java8-installer
      question: shared/accepted-oracle-license-v1-1
      vtype: select
      answer: true

  - name: Install oracle java 8
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
