---
  - name: Install debconf-utils
    apt:
      name: debconf-utils
      state: present

  - name: Make oracle eula to be accepted
    debconf:
      name: oracle-java8-installer
      question: shared/accepted-oracle-license-v1-1
      vtype: select
      value: true

#  - name: Automatically select the Oracle License
#    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

  - name: Install oracle java 8
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
