---
  - name: Make oracle eula to be accepted
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

  - name: Install oracle java 8
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
