---
  - name: Install repos management commons
    apt:
      name: software-properties-common
      state: present

  - name: Add custom repos gpg keys
    apt_key:
      url: "{{ item }}"
      state: present
      validate_certs: "{{ trust_repos }}"
    with_items: "{{ apt_keys }}"

  - name: Add custom apt repos
    apt_repository:
      repo: "{{ item }}"
      state: present
      validate_certs: "{{ trust_repos }}"
    with_items: "{{ custom_repos }}"

  - name: Add phusion repo if needed
    include: phusion.yml
    when: "{{ passenger }}"

  - name: Update apt cache
    apt:
      update_cache: yes
