---
  - name: Install repos management commons
    apt:
      name: software-properties-common
      state: present

  - name: Add custom repos gpg keys by url
    apt_key:
      url: "{{ item }}"
      state: present
      validate_certs: "{{ trust_repos }}"
    with_items: "{{ apt_keys_url }}"

  - name: Add custom repos gpg keys by id
    command: "{{ item }}"
    with_items: "{{ apt_keys_id }}"

  - name: Add custom apt repos
    apt_repository:
      repo: "{{ item }}"
      state: present
      validate_certs: "{{ trust_repos }}"
    with_items: "{{ custom_repos }}"

  - name: Update apt cache
    apt:
      update_cache: yes
