---
  - name: Check if operating system upgrade is needed
    command: /usr/lib/update-notifier/apt-check --package-names
    register: stale

  - name: Upgrade the system if needed
    apt:
      update_cache: yes
      upgrade: dist
    when: stale.stderr != ""

  - name: Reboot if needed
    shell: sleep 2 && /sbin/reboot removes=/var/run/reboot-required
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for hosts to come up
    local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 15
      state: started
