---
  - name: Check if operating system upgrade is needed
    command: /usr/lib/update-notifier/apt-check --package-names
    register: stale

  - name: Upgrade the system if needed
    apt:
      update_cache: yes
      upgrade: dist
    when: stale.stderr != ""

  - name: Reboot if needed
    command: /sbin/reboot removes=/var/run/reboot-required
    async: 0 # should be changed to 1 plus other modifications needed if ansible version is >=1.9.0, see https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
    poll: 0
    ignore_errors: true

  - name: Wait for hosts to come up
    local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 30
      state: started
    sudo: false
